[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
